name: Process TV URLs

on:
  push:
    paths:
      - 'itvlist.txt'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install regex
    
    - name: Run processing script
      run: |
        python process_urls.py
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add processed_itvlist.txt
        git commit -m "Processed TV URLs"
        git push
